theme: jekyll-theme-cayman
title: In brightest day, in blackest night
description: Welcome to Nuño’s lair, with an axiomatic flair for the dramatic, the mathematic, the logical, the philosophical. This is where I will keep those projects of mine which I consider worthy. 
